[package]
name = "sprog"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embedded-graphics = "0.8.1"
embedded-hal = "1.0.0"
embedded-hal-bus = "0.3.0"
embedded-time = "0.12.1"
fugit = "0.3.7"
panic-halt = "1.0.0"
rp-pico = "0.9.0"
st7735-lcd = "=0.9.0"
